# This file contains values from Cookiecutter

default_context:
  project_name: "minhas_financas"
  project_description: "Projeto que desenvolverei para acompanhar minha carteira de investimentos, renda fixa, gastos, e etc, utilizando ferramentas em python, google sheets e Looker Studio."
  organization: "minhas_financas"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "guiccosta"
  email: "gccosta1103@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
